### ISSUE TITLE
ExceptionInInitializerError with java 17

### ISSUE THREAD

**Issue by yaskor** [avaje/avaje-inject#210]
After switching from java 11 to 17, calling the method 

BeanScope beanScope = BeanScope.newBuilder().forTesting().build()

throws following exception:

Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @13eb8acf

**Comment by rbygrave** [comment]
Ok, is that maven, maven-surefire-plugin?  Can you check that you are on version **3.0.0-M6** of the maven-surefire-plugin?

**Comment by rbygrave** [comment]
Noting that we have builds going against EA (Java 19 at the moment) and GA (Java 18 at the moment).

For example, see: https://github.com/avaje/avaje-inject/actions/runs/2304595602

We could / should add **17** to our build matrix though ... https://github.com/avaje/avaje-inject/blob/master/.github/workflows/build.yml#L15

**Comment by rbygrave** [comment]
For comparison, the source of the parent pom for avaje-inject is: https://github.com/avaje-pom/java11-oss/blob/master/pom.xml#L21

**Comment by yaskor** [comment]
Tried surefire 3.0.0-M6, now the exception has more detail, but still fails:

java.lang.ExceptionInInitializerError
	at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
	at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:95)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.spy(Mockito.java:1368)
	at io.avaje.inject.spi.EnrichBean.enrich(EnrichBean.java:27)
	at io.avaje.inject.spi.DBuilderExtn.enrich(DBuilderExtn.java:52)
	at io.avaje.inject.spi.DBuilder.register(DBuilder.java:127)
	at io.avaje.inject.spi.DBuilder.register(DBuilder.java:113)
	at de.yaskor.autocontract.service.EmailService$DI.build(EmailService$DI.java:21)
	at de.yaskor.autocontract.AutocontractModule.build_service_EmailService(AutocontractModule.java:292)
	at de.yaskor.autocontract.AutocontractModule.build(AutocontractModule.java:160)
	at io.avaje.inject.DBeanScopeBuilder.build(DBeanScopeBuilder.java:155)
	at de.yaskor.autocontract.test.ContextExtension.beforeAll(ContextExtension.java:91)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @6a79c292
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:57)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:47)
	... 66 more

**Comment by rbygrave** [comment]
Can you check the Mockito version?

**Comment by yaskor** [comment]
I've tried the newest beta of mockito 2.0.2-beta and still the same problem.
If I remove mockito from my tests, the Initializer Error disapears even with maven-surefire-plugin 2.22.2.

So the problem seems to be in is in mockito I think?

**Comment by rbygrave** [comment]
> maven-surefire-plugin 2.22.2.

That is not 3.0.0-M6 ... you need to bump that to 3.0.0–M6.

**Comment by yaskor** [comment]
I tested both 2.22.2 and 3.0.0–M6.
If I remove mockito the Initializer Error disapears.

**This throws the initializer Error;**
var forTesting = beanScopeBuilder.forTesting();
forTesting.withMock(User.class);
beanScope = forTesting.build();

**This does't**
var forTesting = beanScopeBuilder.forTesting();
beanScope = forTesting.build();

**Comment by rbygrave** [comment]
My thoughts are:

- clone avaje-inject and run it against 17. That will pass, look for differences between that and your project. Maybe compare mvn dependency:tree

- put up a failing test case project, and I can confirm it fails and see if I can get it working

**Comment by yaskor** [comment]
Hi rbygrave,

I made a small project for reproduction:

https://github.com/yaskor/avaje-inject-test

If you try to run the Reproduce.java test, it fails with described exception

**Comment by rbygrave** [comment]
Using a really old version of mockito, need to bump that, details here: https://github.com/yaskor/avaje-inject-test/issues/1

Was:
```xml
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
```

Bumped to:
```xml
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>4.4.0</version>
            <scope>test</scope>
        </dependency>
```

Also, highly highly recommend that absolute latest version of `maven-surefire-plugin` which today is `3.0.0-M6`

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M6</version>
            </plugin>
```

**Comment by rbygrave** [comment]
As a side note: avaje-inject-test has a junit5 extension ... https://avaje.io/inject/#component-testing
... and that has some good improvements (inject static fields &/or non-static fields) in master that will be in the next release.

I'm just looking to add a SPI for "web server component testing" ... such that we can in a test do `@Inject HttpClient` ... and that will automatically lifecycle a web server for that test (as static class level or per test level).

So yeah, just need to add that and then release the next with that plus those nice improvements.

**Comment by yaskor** [comment]
Oh ok, I didn't know that. I've built my own extension.
I will have a look into it.
