### ISSUE TITLE
Test environment injection of external beans

### ISSUE THREAD

**Issue by kevin70** [avaje/avaje-inject#218]
Hello, I need to inject external beans into JUnit environment.
I tried several methods but failed. My configuration uses typesafe config, which is manually initialized.

```
@InjectModule(requires = {Config.class})
```

**META-INF/services/io.avaje.inject.test.TestModule**
```
cool.houge.iris.TestBase$AvaeTestModule
```

TestBase.java
```
public class TestBase {

  public static final Faker faker;
  public static final Config config;

  static {
    faker = Faker.instance(Locale.CHINA);
    config = ConfigFactory.load("iris-test.conf");
  }

  public static class AvaeTestModule implements TestModule {

    @Override
    public Class<?>[] provides() {
      return new Class[0];
    }

    @Override
    public Class<?>[] requires() {
      return new Class[0];
    }

    @Override
    public Class<?>[] requiresPackages() {
      return new Class[0];
    }

    @Override
    public Class<?>[] classes() {
      return new Class[] {Config.class};
    }

    @Override
    public void build(Builder builder) {
      builder.withBean(Config.class, config);
    }
  }
}
```

**exception stacktrace**
```
Module [cool.houge.iris.IrisApplicationModule] has unsatisfied requires [com.typesafe.config.Config] - none of the loaded modules [] have this in their @InjectModule( provides = ... ). Either @InjectModule requires/provides are not aligned? or add external dependencies via BeanScopeBuilder.bean()?
java.lang.IllegalStateException: Module [cool.houge.iris.IrisApplicationModule] has unsatisfied requires [com.typesafe.config.Config] - none of the loaded modules [] have this in their @InjectModule( provides = ... ). Either @InjectModule requires/provides are not aligned? or add external dependencies via BeanScopeBuilder.bean()?
	at io.avaje.inject.DBeanScopeBuilder$FactoryOrder.processQueue(DBeanScopeBuilder.java:278)
	at io.avaje.inject.DBeanScopeBuilder$FactoryOrder.orderFactories(DBeanScopeBuilder.java:235)
	at io.avaje.inject.DBeanScopeBuilder.build(DBeanScopeBuilder.java:145)
	at io.avaje.inject.test.MetaInfo.buildSet(MetaInfo.java:48)
	at io.avaje.inject.test.MetaInfo.buildForInstance(MetaInfo.java:36)
	at io.avaje.inject.test.InjectExtension.beforeEach(InjectExtension.java:103)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:163)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:162)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:129)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by kevin70** [comment]
Hello. I do use the `InjectExtension`.

```
@Generated("io.avaje.inject.generator")
@InjectModule(requires={com.typesafe.config.Config.class})
public class IrisApplicationModule implements Module {
  // ...ellipsis
}
```
There are requirements in the automatically generated module (@InjectModule(**requires={com.typesafe.config.Config.class}**)).
In the unit test initialization environment, I am prompted that I must register external beans through `withBean`.

**Comment by rbygrave** [comment]
I don't think I really understand what you are doing here. I got the impression this was for testing ... so, can you provide a small example project that shows me what you are trying to do. I think that will help.

**Comment by kevin70** [comment]
@rbygrave

**Comment by kevin70** [comment]
https://github.com/kevin70/avaje-inject-samples

I created a sample project. This is the problem I have now.
Thanks.

**Comment by rbygrave** [comment]
Reproduced the issue. The underlying issue is that for the case of "Test scope" we kind of have an extra BeanScope (our global test scope) that is the **_parent_** of all the BeanScopes we create for testing (but we are not using it / checking it for the externally required dependency case).  

For the case where we have an external dependency, the natural and correct thing to do for testing ... is to provide it for the `@TestScope` - the bug/issue is that avaje-inject currently does **_NOT_** use the parent BeanScope to see that the dependency is provided by `@TestScope`.

### That is:
- for "main" we provide the external dependency programmatically.
- for "test" we want to provide it via `@TestScope`  (typically a `@Factory` `@Bean` method)
- the issue is that avaje-inject isn't checking to see if the "parent" has the externally provided bean (which it does in test).


### The fix:
- Modify avaje-inject in DBeanScopeBuilder to check the parent to see if it provides the external dependency

**Comment by rbygrave** [comment]
Dang, I literally forget to release the artifacts from the maven central staging area until just now ... so version 8.5 will be in central in 20mins or so and that includes the fixes for those 2 issues you hit.

Cheers, Rob.
